// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { Capacitor } from '@capacitor/core';
import { capacitorStorage } from '@/lib/capacitorStorage';
import { logger } from '@/lib/logger';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://vrzmfhwzoeutokzyypwv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "YOUR_ANON_KEY_HERE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// ✅ BUILD 28: Usar método correto para detectar plataforma nativa
const isNativePlatform = Capacitor.isNativePlatform();

// ✅ FASE 1: Lazy initialization - client só é criado quando requisitado
let _supabaseInstance: ReturnType<typeof createClient<Database>> | null = null;

export const getSupabase = () => {
  if (!_supabaseInstance) {
    // ✅ BUILD 51: Logging detalhado incluindo fallback mode
    const usingFallback = isNativePlatform && !capacitorStorage.initialized;

    logger.info('Supabase Client', 'Creating client instance', {
      isNativePlatform,
      storageInitialized: isNativePlatform ? capacitorStorage.initialized : 'N/A (web)',
      fallbackMode: usingFallback,
      timestamp: Date.now()
    });

    // ✅ BUILD 51: SEMPRE permitir criação (usar localStorage como fallback)
    if (usingFallback) {
      logger.warn('Supabase Client', '⚠️ Using localStorage fallback (storage not ready)', {
        hint: 'Storage will be migrated in background'
      });
    }

    // ✅ BUILD 51: Decidir storage baseado na disponibilidade
    const storage = (isNativePlatform && capacitorStorage.initialized)
      ? capacitorStorage
      : localStorage;

    _supabaseInstance = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage, // ✅ localStorage ou capacitorStorage (o que estiver pronto)
        persistSession: true,
        autoRefreshToken: true,
        detectSessionInUrl: false,
        flowType: 'pkce',
      },
      realtime: {
        params: {
          eventsPerSecond: 10,
        },
        timeout: isNativePlatform ? 15000 : 10000,
        heartbeatIntervalMs: 30000,
      },
      global: {
        headers: {
          'X-Client-Info': 'app-modelo-mobile/1.0',
          'X-Platform': isNativePlatform ? 'capacitor' : 'web',
        },
      },
    });

    logger.info('Supabase Client', 'Client created successfully');

    // ✅ FASE 5: Request interceptor for detailed logging (dev only)
    if (import.meta.env.DEV) {
      const originalFetch = window.fetch;
      window.fetch = async (...args) => {
        const url = args[0]?.toString() || '';

        // Log only Supabase requests
        if (url.includes('supabase.co')) {
          console.log('🌐 Supabase Request:', {
            url: url.replace(/apikey=[^&]+/, 'apikey=***'),
            method: args[1]?.method || 'GET',
            timestamp: new Date().toISOString()
          });
        }

        try {
          const response = await originalFetch(...args);

          if (url.includes('supabase.co') && !response.ok) {
            console.error('❌ Supabase Response Error:', {
              url: url.replace(/apikey=[^&]+/, 'apikey=***'),
              status: response.status,
              statusText: response.statusText
            });
          }

          return response;
        } catch (error: any) {
          if (url.includes('supabase.co')) {
            console.error('❌ Supabase Fetch Error:', {
              url: url.replace(/apikey=[^&]+/, 'apikey=***'),
              error: error?.message || 'Unknown error'
            });
          }
          throw error;
        }
      };
    }
  }

  return _supabaseInstance;
};

// ✅ BUILD 51: Proxy SEM guard (permitir sempre, usar localStorage fallback)
export const supabase = new Proxy({} as ReturnType<typeof createClient<Database>>, {
  get(target, prop) {
    // ✅ BUILD 51: NUNCA bloquear - getSupabase() decidirá o storage
    const client = getSupabase();
    return client[prop as keyof ReturnType<typeof createClient<Database>>];
  }
});

// Export da chave pública para uso direto em fetch
export const SUPABASE_KEY = SUPABASE_PUBLISHABLE_KEY;